### ISSUE TITLE
Apex

### ISSUE THREAD

**Issue by Effectik** [SteelSeries/gamesense-sdk#1]
Not work on Apex keyboard with examples "audiovisualizer"

**Comment by davidtibbetts** [comment]
The Apex and Apex[RAW] don't have independent lighting on every key, so the audiovisualizer example was only implemented to work on the M800. 
For the Apex, and only 5 zones of color, we're open to suggestions on how the audiovisualizer example could work on it.
Thanks for checking out the gamesense-sdk!
