### ISSUE TITLE
Npm package active again

### ISSUE THREAD

**Issue by DaanWet** [SteelSeries/gamesense-sdk#102]
In the documentation about [sending game events](https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/sending-game-events.md) it states that the javascript npm library is inactive, that has changed. I contacted the original owner and he transfered the package (and repo) to me, the repo is now available at https://github.com/DaanWet/gamesense-client and will be kept up to date in the future
(Up to date and new examples coming soon)

**Comment by JHunz** [comment]
The documentation has been updated to reflect this
