### ISSUE TITLE
Detect keyboard key strokes using the SDK

### ISSUE THREAD

**Issue by elemen7s** [SteelSeries/gamesense-sdk#108]
Hi, Is it possible to detect key strokes from a steelseries keyboard, specifically the steelseries special key which is used for the meta bindings? 

I have looked through the documentation but couldn't find anything mentioning such feature.

I am asking for this as I would like to implement some custom features for my own use which will be triggered using the meta bindings since the SteelSeries Engine doesn't allow you to do so.

Thanks in advance

**Comment by JHunz** [comment]
No, sorry, the SDK does not allow input interception or detection.
