### ISSUE TITLE
Wrong documentation for range-screen-data

### ISSUE THREAD

**Issue by DaanWet** [SteelSeries/gamesense-sdk#109]
In the [schema overview](https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/json-handlers-screen.md#full-schema-definition) range-screen-data-definition is one object while static-screen-data-definition is an array of screen-frame-data
If you look at the documentation further on the page you notice that the [json data](https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/json-handlers-screen.md#ranged-frame-data) uses a list of such objects. I suppose this is the correct way of doing it?

**Comment by JHunz** [comment]
The "datas" key of the range-screen-data-definition references the schema type static-screen-data-definition, which is the array of objects.  That is how it is used in the example as well.

**Comment by JHunz** [comment]
The earlier comment I left was incorrect, I see the problem you're pointing out now.  I'll get that corrected.

**Comment by JHunz** [comment]
I've updated the schema documentation
