### ISSUE TITLE
Add Rust bindings

### ISSUE THREAD

**Issue by ptrstr** [SteelSeries/gamesense-sdk#110]
I have recently made Rust bindings to the API. Should the [repo](https://github.com/ptrstr/gamesense) and [crate](https://crates.io/crates/gamesense) be added to the documentation? A few endpoints are lacking but it works with the basic ones and OLED.

Thanks!

**Comment by JHunz** [comment]
The repo and crate are now linked in the documentation.  I hope to see it fully developed!
