### ISSUE TITLE
InternalServerError when binding full keyboard effect.

### ISSUE THREAD

**Issue by habetuz** [SteelSeries/gamesense-sdk#113]
Hello,
my goal is to make a full keyboard effect. I followed the [Documentation](https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/json-handlers-full-keyboard-lighting.md#full-keyboard-effects).
My binding request looks the following:
```
{
  "game": "KALE",
  "event": "KEYBOARD_BITMAP",
  "icon_id": 0,
  "min_value": 0,
  "max_value": 1,
  "value_optional": true,
  "handlers": [
    {
      "device_type": "rgb-per-key-zones",
      "mode": "bitmap"
    }
  ]
}
```
The server responses the following:
`Status: InternalServerError | Content: {"error": {"message": "Something bad happened"}}`

Any help on how to fix this error is welcome!

**Comment by JHunz** [comment]
I think that should be `device-type`, not `device_type`.  I'll look into why it's not providing you a more informational error message in this case.

**Comment by habetuz** [comment]
Oh, what a silly mistake!
Nevertheless it's kind of annoying that the engine expects `device-type` and not `device_type`, because I write in c# where you are not allowed to have identifiers with a "-".
It would be easy to just change all underscores to "-" but unfortunately `min_value`, `max_value`, `icon_id` etc. require underscores.

Nonetheless, thank you for the fast response!
