### ISSUE TITLE
Custom GameSense Application Icons

### ISSUE THREAD

**Issue by mbrewerton** [SteelSeries/gamesense-sdk#12]
Hi, I've been working on an application that uses GameSense, and I was wondering if there's any way to get a custom Game Icon in Engine without it being an official game added by SteelSeries.

This isn't a necessity, just a feature that I was wondering is possible, I'm more than happy with the default icons, just curious.

**Comment by JHunz** [comment]
Adding custom application icons isn't currently supported by the API, and is unlikely to be for various user experience reasons.  However, if you link a 32x32 PNG (with transparency) of the icon you want to use, and tell me what the game name is that you're using, I'd be happy to throw it in the next release so the icon shows up when that game name is used (assuming designer approval of your icon).

**Comment by mbrewerton** [comment]
Hi, thanks for getting back. I'm not actually writing code for a game per se, it's a bit of a (hopefully) unique background app that will be utlising GameSense to do some pretty nifty things.

When it's complete, is there some sort of approval process to get it included in Engine for all to use? As I said it's not for a game, it will act as a Windows app in its own.

**Comment by JHunz** [comment]
When I said "game name", I just meant the key you're passing to the "game" parameter when registering the app.  
  
The way we designed the JSON API, we don't need to approve anything for you to distribute your app yourself and have it work natively with all SSE3 installs that support GameSense (3.4 up).  If you want the app itself to be included with SSE3, we don't have any standard approval process for that.  We'd be happy to take a look at it once it's done, though.

**Comment by dastels** [comment]
@mbrewerton I'm quite interested in what you're doing. In fact, I've been spending some of my time writing small example non-game apps that make use of GameSense. I'd welcome the opportunity to talk with you about what you're working on.

**Comment by mbrewerton** [comment]
@JHunz I see what you mean now! When the project gets a bit further down the line I may look into creating a quick logo design, thank you for the information and thank you for the offer to include the icon as well!

@dastels I'm pleased to hear that you're interested! I'd love an opportunity to discuss the project further with you, I'm finding GameSense a joy to work with. I had a few trip-ups along the way, but nothing a quick re-read of the documentation I missed couldn't solve!

**Comment by brainbug89** [comment]
> Adding custom application icons isn't currently supported by the API, and is somewhat unlikely to be for various user experience reasons.

Is that still the case? I would like to add custom icons for my applications. What are the "various user experience reasons"?

**Comment by M4FFS** [comment]
+1,  would like custom icons :(
