### ISSUE TITLE
Won't react to other event

### ISSUE THREAD

**Issue by Hely0n** [SteelSeries/gamesense-sdk#121]
I have two bound events for the oled screen. Everything works as it should. Event A gets send and the screen reacts. Now I send event B, and the screen changes accordingly, and reacts to all event B. But now it doesn't react to event A anymore until re-binding the events.

Sometimes, it works but only once or twice, and it seems like in random situations.

**Comment by Hely0n** [comment]
Well, I just found the problem. It won't react to events with unchanged values.
Had to do some workarounds against it.

**Comment by ToadKing** [comment]
The correct way to always handle events even if the value doesn't change is to use the `value_optional` property when registering the event. See the bottom of the [sending game events](https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/sending-game-events.md) documentation.

**Comment by Hely0n** [comment]
Oh I see, thank you!
