### ISSUE TITLE
Reading key press distance

### ISSUE THREAD

**Issue by okunamayanad** [SteelSeries/gamesense-sdk#136]
On OmniPoint switches can read the depth of how far the key has been pressed. I couldn't find any documentation of how I can grab that data. Is there a way for me to get this value? This can be valuable for racing games to bind WASD keys to simulate joystick behaviour or an illumination effect where your key and its neighbours can light up depending on how far you press the key.

**Comment by JHunz** [comment]
This isn't something exposed by the API, sorry

**Comment by okunamayanad** [comment]
So it's not possible? Ok. Closing this as not planned then
