### ISSUE TITLE
Docs: *Writing Handlers in JSON* is incomplete.

### ISSUE THREAD

**Issue by carlsmith** [SteelSeries/gamesense-sdk#15]
In the *Writing Handlers in JSON* doc, in the section *Specifying a device type*, it says "For a list of valid device type strings, see `Reference Sections - Device types` below". The section doesn't seem to exist. There is [a separate document][1] (standard-zones.md) that includes the information, but *Writing Handlers in JSON* doesn't point you to it.

[1]: https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/standard-zones.md

**Comment by davidtibbetts** [comment]
Good catch, carlsmith. We are planning a big update to the GameSense SDK soon. This is now on the list, thanks!

**Comment by carlsmith** [comment]
No problem.

Having an engine that anyone can easily hook into, especially with OS X support, is really nice. I don't even game, but got a mouse, and liked it so much, I got a matching headset for working from home. Keep up the good work guys!
