### ISSUE TITLE
Rival100 on-device doesn't works.

### ISSUE THREAD

**Issue by HAWK0044** [SteelSeries/gamesense-sdk#16]
Looks like both of 
(on-device 'mouse show-on-zone: c one:) and (on-device 'mouse show-on-zone: c two:) doesn't works with Rival 100. I've created myrgb.lsp in hax0rbindings, and event in it "SETRGB2" (it's strange that old events which was used from game_event doesn't appears in SSE while are in .lsp script. 

There is the code of myrgb.lsp:
`(handler "SETRGB2"
  (lambda (data)
    (let*	((v (value: data))
			(c (color-between red-color green-color v))
	  (on-device 'mouse show-on-zone: c one:)
	  (on-device 'mouse show-on-zone: c two:)))))`

I've tried to execute it from POST request with args:
{
    "game":"MYRGB",
    "event":"SETRGB2",
    "data":{"value":1}
}

but it doesn't works, for sure, if I pass bad value in "value" I'll get an error in golisp-log.txt

**Comment by ToadKing** [comment]
I belive your handler code is incorrect. It looks like this:

```scheme
(handler "SETRGB2" (lambda (data)
  (let* ((v (value: data))
         (c (color-between red-color green-color v))
         (on-device 'mouse show-on-zone: c one:) (on-device 'mouse show-on-zone: c two:)))))
```

Note the `on-device` calls are inside the `let` local binding parameters, not in the code that runs after them. I believe this code should work:

```scheme
(handler "SETRGB2" (lambda (data)
  (let* ((v (value: data))
         (c (color-between red-color green-color v)))
         (on-device 'mouse show-on-zone: c one:) (on-device 'mouse show-on-zone: c two:))))
```

**Comment by ToadKing** [comment]
I should also note that the Rival 100 only has one illumination zone that covers both the mouse wheel and the logo.

**Comment by HAWK0044** [comment]
oh, well. Thank you a lot, I didn't wrote on lisp before so it was hard to
notice for me :)

2016-06-16 19:47 GMT+03:00 Toad King <notifications@github.com>:
