### ISSUE TITLE
Binding Event on Rival 700 Causes SteelSeries Engine 3 Software to Crash

### ISSUE THREAD

**Issue by tomizechsterson** [SteelSeries/gamesense-sdk#26]
I've noticed that binding an event using bind_game_event will subsequently cause the software to crash on startup (first attachment below). Requests sent to the API are all successful, as can be seen in the second screenshot of DHC in Chrome. Registering and removing a test game seems to work just fine; it's just binding an event that appears to offend SteelSeries Engine 3. Also, removing the event will calm the software down and allow it to startup, and events sent to the Rival 700 all seem to produce the expected results in my testing, despite the software being upset. In case it's helpful, I've also attached the errorlog.txt and nw-log.txt files below the screenshots.

Update: Just realized that color-related events don't seem to cause this issue

My event-related request bodies look like this:
- bind_game_event
```json
{
"game":"TESTGAME",
"event":"TESTEVENT",
"handlers": [{
	"device-type": "screened",
	"zone":"one",
	"mode":"screen",
	"datas": [{
		"has-text":true
		}]
	}]
}
```
- game_event
```json
{
"game":"TESTGAME",
"event":"TESTEVENT",
"data":{
	"value": "TEST!"
	}
}
```
- remove_game_event
```json
{
"game":"TESTGAME",
"event":"TESTEVENT"
}
```

![errorfromprogram](https://cloud.githubusercontent.com/assets/19846001/19408150/33d8d970-926b-11e6-935d-ceb57ce741e4.jpg)

![requests](https://cloud.githubusercontent.com/assets/19846001/19408153/586354aa-926b-11e6-8f04-66f3ee16b413.png)

[errorlog.txt](https://github.com/SteelSeries/gamesense-sdk/files/530855/errorlog.txt)

[nw-log.txt](https://github.com/SteelSeries/gamesense-sdk/files/530856/nw-log.txt)

**Comment by JHunz** [comment]
Thanks for the detailed report!  We'll get it sorted out

**Comment by tomizechsterson** [comment]
Awesome, thank you. Looking forward to it. And if I can help in any way, feel free to let me know

**Comment by JHunz** [comment]
The fix above will go live with SSE 3.9.2

**Comment by ToadKing** [comment]
To work around this for the time being, you can add an `arg` property to the event handler.

```json
{
"game":"TESTGAME",
"event":"TESTEVENT",
"handlers": [{
    "device-type": "screened",
    "zone":"one",
    "mode":"screen",
    "datas": [{
        "has-text":true,
        "arg":"(value: self)"
        }]
    }]
}
```

**Comment by tomizechsterson** [comment]
I'll try that. Thank you for looking into this!

**Comment by tomizechsterson** [comment]
@ToadKing, I just tried the event handler you posted, and unfortunately SSE is still crashing on startup after binding it. Here's the updated nw-log.txt file with the new entries for today at the bottom:

[nw-log.txt](https://github.com/SteelSeries/gamesense-sdk/files/540811/nw-log.txt)

Also, a screenshot of DHC in Chrome with the bind_game_event request:
![image](https://cloud.githubusercontent.com/assets/19846001/19546811/87d7ed56-9647-11e6-9af3-1351f4231a8f.png)

And the body of the response (sorry I forgot to include this in my original post):
{"game_event_binding": {"game":"TESTGAME","event":"TESTEVENT_TEXT","icon_id":0,"min_value":0,"max_value":0,"HandlerDatas":["{\"datas\":[{\"arg\":\"(value: self)\",\"has-text\":true}],\"device-type\":\"screened\",\"mode\":\"screen\",\"zone\":\"one\"}"],"handlers":[{"datas":[{"arg":"(value: self)","has-text":true}],"device-type":"screened","mode":"screen","zone":"one"}]}}

**Comment by ToadKing** [comment]
It looks like the old handler data is still being returned to the frontend. That's odd, but that sounds like a different issue other than the crash. I'll make a note of that and look into it.
