### ISSUE TITLE
Get assigned Macros with API

### ISSUE THREAD

**Issue by DeeTrueSnyder** [SteelSeries/gamesense-sdk#31]
I've reviewed the documentation but haven't been able to find a way to request what the current macro and/or key stroke assignment is with the API. Am I just missing it or is this not supported?

Little bit of background on what I want to do. I'd like to create a rainmeter plugin displays my keyboard and mouse configuration on the screen for a few seconds before fading away. Rather then having to hard code the rainmeter plugin with my current configuration and update it when I make changes to my hardware config I'd like it to fetch the individual key names, their currently assigned macro name or key stroke. 

It looks like the standard-zones.md is pretty close to what I want but doesn't return info about the zone. 

Thanks in advance.

**Comment by JHunz** [comment]
GameSense, as designed, is a one-way API for application developers to be able to send information about the state of their application/game to SteelSeries Engine.  It was not designed for the opposite use case and it is unlikely that we will ever implement anything like that in the API for reasons of user privacy.  There are certainly ways to get the information you're looking for from your local installation, but not through the GameSense API.
