### ISSUE TITLE
GameSense not working for minimal example

### ISSUE THREAD

**Issue by brainbug89** [SteelSeries/gamesense-sdk#33]
I want to do something like this: https://github.com/SteelSeries/gamesense-sdk/issues/32#issuecomment-306593793
So first I tried to build a minimal working example. My test.lsp file looks like this:
```
(handler "TESTEVENT"
  (lambda (data)
    (let* ((val (value: data))
           (c (color-between red-color blue-color val))
      (on-device "headset" show-on-zone: c earcups:)))))
```

and part of the html-file to create and send json game events:
```
<script type="text/javascript">
var sseAddress = "127.0.0.1:64998"
var GAME = "TEST"

var test_event = function() {
    var testEventRequest = new XMLHttpRequest();
    var inputvalue = parseInt(document.getElementById("inputValue").value, 10);
    var payload = {
        "game": GAME,
        "event": "TESTEVENT",
        "data": {
            "value": inputvalue
        }
    };
    try {
    	var url = "http://" + sseAddress + "/game_event";
        testEventRequest.open("POST", url, true);
        testEventRequest.setRequestHeader("Content-Type", "application/json");
        testEventRequest.send(JSON.stringify(payload));
        testEventRequest.onreadystatechange = function() {
            if (testEventRequest.readyState == XMLHttpRequest.DONE) {
                //alert("test_event: done");
            }
        };
    } catch (e) {
    	console.error(e);
    }
}
```
I'm modifying the `sseAddress` with coreProps.json for every start of SSE.

If I'm using `/bind_game_event` to create json event handler, everything works fine. But if I'm using golisp handler, it doesn't work: the color cycling of the headset stops (so GameSense is receiving the event), but it doesn't show the selected color. And after 15 sec (timeout) the color cycling starts again.

What's wrong with my code? (Edit: I'm testing with a Siberia v3 Prism and a Rival)

**Comment by ToadKing** [comment]
The parenthesis on your `let*` statement appear to be incorrect. Try this:

```scheme
(handler "TESTEVENT"
  (lambda (data)
    (let* ((val (value: data))
           (c (color-between red-color blue-color val)))
      (on-device "headset" show-on-zone: c earcups:))))
```

**Comment by brainbug89** [comment]
wow this response was fast and it works! thank you very much :smile:

**Comment by ToadKing** [comment]
Glad I could help and thanks for pointing that out!
