### ISSUE TITLE
Game_metadata JSON datas

### ISSUE THREAD

**Issue by sqpp15** [SteelSeries/gamesense-sdk#35]
Hi!

How can I see the list of available meta?

Example:
```
  "game": "CS2D",
  "game_display_name": "CS2D",
  "developer": "Marcell Csendes",
  "icon_color_id": 5
```

I need a link for like Discord
![image](https://user-images.githubusercontent.com/25447110/29529899-cc0c368a-86a1-11e7-883b-253ac2742e31.png)

and for the image, since  right now it looks like this:

![image](https://user-images.githubusercontent.com/25447110/29529919-e167affa-86a1-11e7-958a-d4c078f3bd53.png)

**Comment by sqpp15** [comment]
The game actually will not include this anyway, so basically it totally unnecessary to start this project. :(

**Comment by Treer** [comment]
I'd still like to know if there's a way to set the image for gamesense app. Additional apps look very second-class-citizen with their empty box for a splashscreen.
