### ISSUE TITLE
Sending full RGB Data

### ISSUE THREAD

**Issue by Darkete** [SteelSeries/gamesense-sdk#37]
Hey, im making an LED controller that uses JSON to send the data. I also have an Arctis 5 headset. I'm searching for the way to sync that Controller with my Arctis 5. I been reading about GameSense but all examples uses a gradient value, and i need to send the RGB value. Is there any way to bypass the gradient ?

**Comment by JHunz** [comment]
The JSON color handlers document describes how to send a static color.  It's also present in the example at the bottom labeled "Show a count on the M800's 1-5 macro keys. Use a solid white color, and don't flash"

It's just a matter of specifying the color key as an object with subkeys "red", "green", and "blue":
"color": { "red": 255, "green": 0, "blue": 0 }

**Comment by NitroBAY** [comment]
I'm in the case of this person and I would like to know if we can change the color of our headset without creating a handler that is not very relevant in the case of just sending the plain color.

**Comment by NitroBAY** [comment]
@JHunz

**Comment by NitroBAY** [comment]
I guess I could use a complex range based system but this seems super overkill when I just would like sending the color
