### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by vec3h** [SteelSeries/gamesense-sdk#42]
So, i could not find any info about creating permanent non-game plugin. E.G i want to display time on my Rival 700 screen, how can i do it?

**Comment by mbrewerton** [comment]
The way I did it with my Apex M800 was i made a windows application to run in the background and registered that as a game via the API (https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/writing-handlers-in-json.md).

**Comment by vec3h** [comment]
Thanks, maybe there is another way to do it?

**Comment by mbrewerton** [comment]
Not that I'm aware of. The GameSense API requires an application to POST json data to the endpoints. I have a Sensei, not a Rival so I can't answer for certain, but from my knowledge I'm pretty sure your only option is some sort of background process. It's a pretty nifty idea though, if I had a Rival I'd consider writing the code.

**Comment by davidtibbetts** [comment]
@mbrewerton is correct. The GameSense SDK just provides a method for any program on your machine to send POST JSON data to SSE's endpoint. There is no plug-in method/API. One of the main reasons for this API design is, it allows for clients to be written in any language you want, where the only requirement is that messages are sent via a specific protocol. This also gives developers much more flexibility to add GameSense support to an existing codebases.
