### ISSUE TITLE
SSE3 vs PRo wireless Problem.

### ISSUE THREAD

**Issue by Spaden89** [SteelSeries/gamesense-sdk#44]
Hi. let me just start by saying I know this is the wrong way to get help. But they have tried to close my ticket 2 times now whit out solving the problem I'm having. 

The problem I'm having is when I'm trying to connect the transmission box to SSE3 I'm getting this error. 

" Warning The core process SteelSeriesEngine3.EXE does not seem to be running."
If someone has some tip that I can trie please let me know.  I can provide all logs and everything if someone will need it.  The Request number I'm having at support now is  (#545098)

Best regards Rasmus

**Comment by ToadKing** [comment]
Please try following the instructions in this post: https://www.reddit.com/r/steelseries/comments/8p3noj/need_urgent_help_with_my_new_arctis_pro/e0aqic1/

If that doesn't work then please follow up in your ticket.
