### ISSUE TITLE
Building an IFTTT-like app

### ISSUE THREAD

**Issue by vprasanth** [SteelSeries/gamesense-sdk#59]
Hi, note sure where else to ask. But I'm trying to determine if I can use the SDK (or some other interface via gamesense) to control rgb on my keyboard for tasks outside of gaming. Basically like an IFTTT for the kb... is this doable? I'm also on OSX and not sure if I'm even able to develop on this platform. Any advice here would be grateful!

**Comment by szabolcs-dekany92** [comment]
The endpoint uses JSON to communicate. If you can send a JSON request from the app you are developing to the endpoint, you are good to go.

**Comment by mbrewerton** [comment]
As @szabolcs-dekany92 has said, the endpoint just uses JSON. If setup correctly following the guides, you'll have an endpoint to make POST requests to. The technology you use for this makes no difference as you're just POSTing and receiving JSON data.

I was working on a project in .Net using C# and it was extremely simple to get going.

**Comment by vprasanth** [comment]
Thank you, sorry I didn't properly go over the readme md files! Now I just need to find a local store with an apex kb in stock T__T

**Comment by Treer** [comment]
@mbrewerton what happened to your app - is it public?

I don't really know what's out there, as there's no place to see the standalone GameSense apps. This also risks me reinventing the wheel.

**Comment by vprasanth** [comment]
@Treer It's funny you should mention that. My thoughts exactly, I think there's a missed opportunity there. Like what npm is to nodejs, something like that for kb apps.

**Comment by dastels** [comment]
We had talked about doing something like that.

Dave

**Comment by vprasanth** [comment]
> We had talked about doing something like that.

Count me in if you need volunteers.
