### ISSUE TITLE
Broken link in writing handlers in json.md file

### ISSUE THREAD

**Issue by wvanbreukelen** [SteelSeries/gamesense-sdk#6]
There is a broken link in the blob/master/doc/api/writing-handlers-in-json.md file, see for the hyperlink Zones by device type.

This link is pointing to the following URL:
https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/standard-zones.md

But this file does not exists

I added a fix, see pull request #7

**Comment by ToadKing** [comment]
Fixed with 5fee293a9327192f98e09314e0b2665a7113c20f
