### ISSUE TITLE
Handler for MSI Mystic Light not working.

### ISSUE THREAD

**Issue by JFiset** [SteelSeries/gamesense-sdk#65]
Trying to create an Handler through json that would affect the keyboard keys and the back of an MSI laptop.

Sending the game_event changes the keyboard color as expected but not the Mystic Light on the back of the laptop. The documentation states: "rgb-24-zone: Any connected, supported, twenty-four zone RGB device. Covers the MSI Mystic Light."

 Using the json handler attached here: [JSONHandler.txt](https://github.com/SteelSeries/gamesense-sdk/files/3065890/JSONHandler.txt), the keyboard reacts properly but not the MSI Mystic Light. The MSI Mystic Light just keeps doing whatever was set using the Steel Series Engine 3.

**Comment by JHunz** [comment]
Are you on the latest public version of SteelSeries Engine (3.13.10)?  That type was actually added to that device recently.

**Comment by JFiset** [comment]
HEY! It worked! Thank you so much!

Updating to the latest version fixed it.
