### ISSUE TITLE
Removing an event or game

### ISSUE THREAD

**Issue by lkroliko** [SteelSeries/gamesense-sdk#67]
When I remove event or game SteelSeries Engine 3 app still shows this. After restart application removed object disappear in menu.
I think this should work in the same way as registering. When registering game or event it shows in menu without application restart.

**Comment by JHunz** [comment]
Good idea, I'll put it on my list of things to do

**Comment by lkroliko** [comment]
I really appreciate that. Thank you.

**Comment by JHunz** [comment]
This change is merged for the next public release (3.15.3)
