### ISSUE TITLE
Apex 7 OLED Display not responding to requests on SSE3 REST Endpoint

### ISSUE THREAD

**Issue by AleAntunez** [SteelSeries/gamesense-sdk#71]
Im trying to create a simple Visual Studio Code extension in order to provide several insights of the editor to the Apex 7 OLED Screen via the REST API exposed by the SteelSeries Engine 3 app.

Although I have been reading the documentation, It looks like something is wrong. I register the application using bind_event, I enable it on the GameSense app, and I start sending heartbeats and data to the app, but the OLED display keep showing the "SteelSeries" logo.

Im attaching the full extension code here in case you could shed me some light about the issue.

https://pastebin.com/6zMyttei

EDIT: 

Numeric data is correctly represented on the device OLED screen, but string data causes SSE3 to crash or send "Server error" responses. A bug-fix on SSE3 is expected.

Thanks a lot for your support.
Regards.

**Comment by JHunz** [comment]
The "event context data" section of the sending events document describes the intended way to send string data: https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/sending-game-events.md#event-context-data  
  
In your handler, you would then access it using the "context-frame-key" property.  You might also want to set the value_optional key when registering the event, so you don't need to include a "value" key if there's no numerical data to represent.  
  
And I've noticed while answering this that part of the document still says the "value" key can be an arbitrary type - this is no longer true and I'll update that section of the document to reflect it.

**Comment by JHunz** [comment]
P.S.  If you can actually crash SSE (not just get a server 500) by sending data to the GameSense API, please provide further details here or privately through the developer contact form: https://steelseries.com/developer/contact-us
