### ISSUE TITLE
Binding OLED screen event with multiple lines crashes Steelseries Engine

### ISSUE THREAD

**Issue by wolfinabox** [SteelSeries/gamesense-sdk#79]
Trying to write multiple lines of text on the OLED screen of my Apex 7 keyboard.
I'm sending this JSON packet to `<url>/bind_game_event`:

```
{
    "game": "SONG_INFO",
    "event": "SONG",
    "min_value": 0,
    "max_value": 100,
    "icon_id": null,
    "handlers": [
        {
            "device-type": "screened",
            "mode": "screen",
            "zone": "one",
            "datas": [
                {
                    "lines": [
                        {
                            "has-text": true,
                            "context-frame-key": "line1",
                            "bold": true
                        },
                        {
                            "has-text": true,
                            "context-frame-key": "line2"
                        },
                        {
                            "has-text": true,
                            "context-frame-key": "line3"
                        }
                    ]
                }
            ]
        }
    ]
}
```
After sending that, going to SteelSeries Engine -> Apps -> my app -> Screen causes a "FATAL ERROR" popup. The request, however, gets a 200 OK response.

I've attached the errorlog.txt and nw-log.txt, but golisp-log.txt and stdout.txt are empty.
[errorlog.txt](https://github.com/SteelSeries/gamesense-sdk/files/4525230/errorlog.txt)
[nw-log.txt](https://github.com/SteelSeries/gamesense-sdk/files/4525231/nw-log.txt)

I'm sending this from Python 3.8.2, on Windows 10 64bit. Steelseries Engine version 3.17.6.

**Comment by JHunz** [comment]
I believe this is the same problem as this issue: https://github.com/SteelSeries/gamesense-sdk/issues/78

The public update with the fix will be rolling out soon, but you can avoid the crash by adding the metadata as detailed in my answer to the other issue

**Comment by wolfinabox** [comment]
@JHunz 
That does indeed seem to fix it, thank you!
