### ISSUE TITLE
Data property

### ISSUE THREAD

**Issue by RoyBekkering** [SteelSeries/gamesense-sdk#8]
Data property in (GameEvent) is a stringified(serialized) string of an object. This should be a normal JSON child property containing the object

**Comment by davidtibbetts** [comment]
The value of `data` in an event is meant to be a stringified JSON object. It is this way in the API for various reasons.
It is documented in [sending game events](https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/sending-game-events.md).

From the documentation:
<HR>
```
{
  game: "MY_GAME",
  event: "HEALTH",
  data: "{\"value\": 75}"
}
```
Notes about the data:
* The values for `game` and `event` are limited to uppercase A-Z, 0-9, hyphen, and underscore characters.
* All three of the keys are mandatory for the event to be processed.
* <B>The value for `data` is a string containing the stringified form of a JSON object.  Any events that will be handled by the JSON API *must* contain the key `value`.  For simplicity and greatest compatibility with user configurability of these events in SteelSeries Engine, it is recommended that the event data be a single `value` key with numeric values.</B>

<HR>


We appreciate you checking out the gamesense-sdk! Please read the documentation before submitting issues.

Thanks,
-Dave

**Comment by ToadKing** [comment]
GameSense was updated in [3.4.1](http://techblog.steelseries.com/2015/07/21/new-in-3.4.1.html) to support passing either JSON strings or raw objects for handlers or event data.
