### ISSUE TITLE
Bind Event does not work

### ISSUE THREAD

**Issue by hypfvieh** [SteelSeries/gamesense-sdk#81]
I'm trying to bind an event using the JSON API and I'm currently using the latest release of SteelSeries Engine (as time of writing: v3.17.6).

Unfortunately every attempt to bind an event fails, even when sending the sample message [provided in the docs](https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/writing-handlers-in-json.md#binding-an-event).

Registering the application sending a request to /game_metadata is working, the application is also appearing in SteelSeries Engine 3.

Here is short log of my application:
`Posting message: "{ "game": "MY_TEST_APP", "game_display_name": "Bind Event", "developer": "Me" }" to: "http://127.0.0.1:XXXXX/game_metadata"
Result: Success: {"game_metadata": {"game":"MY_TEST_APP","game_display_name":"Bind Event","icon_color_id":0,"deinitialize_timer_length_ms":15000,"developer":"Me"}}

App registered, binding event:
Posting message: "{"game": "MY_TEST_APP","event": "MY_EVENT","min_value": 0,"max_value": 100,"icon_id": 1,"handlers": [{"device-type": "keyboard","zone": "function-keys","color": {"gradient": {"zero": {"red": 255, "green": 0, "blue": 0},"hundred": {"red": 0, "green": 255, "blue": 0}}},"mode": "percent"}]}" to: "http://127.0.0.1:XXXXX/bind_game_event"
Result:
Failed (400): {"error": "Game or event string not specified"}
Event binding failed`

Am I missing something? Is the documentation outdated?

**Comment by JHunz** [comment]
Have you made sure you're setting the header "Content-Type:application/json" on the request?

**Comment by hypfvieh** [comment]
The header is correct, I can see that in the debugger.
Also I use the same method to do the game_metadata message which is accepted, as you can see in the log of my application above.

Is their any option to enable some kind of debugging output in the steelseries engine?

**Comment by hypfvieh** [comment]
Never mind, found an issue in my code screwing up the encoding?! (wtf...)
