### ISSUE TITLE
OLED Event frame won't change values when given diffrent one

### ISSUE THREAD

**Issue by EranVazana** [SteelSeries/gamesense-sdk#88]
I have the following Event:

const my_event = {
            game: "MY_APP",
            event: "MY_EVENT",
            handlers: [{
                "device-type": "screened",
                "mode": "screen",
                "datas": [
                    {
                        "lines": [{
                            "has-text": true,
                            "context-frame-key": "headline",
                            "prefix": "Foo - ",
                            "bold": true,
                        },
                            {
                                "has-text": true,
                                "context-frame-key": "subline"
                            },
                            {
                                "has-progress-bar": true,
                                "context-frame-key": "progress"
                            }
                        ]
                    }
                ]
            }]
        };

This event is sent to the engine with the `/bind_event` path.

Later on the main function the following event data is sent on a for loop with the number value being 1 - 10:

var event_data = {
            game: "MY_APP",
            event: "MY_EVENT",
            data: { frame: {headline: "bar", subline: number, progress: number}}

};

My Apex 7 TKL OLED shows on the first event being sent the next image:
- Foo-bar
- 1
- "a progress bar with the 1 value"

The image is displayed as exactly as i wanted.

Next with a delay of 1 second another event with the value of 2, but the same image as before with the values of 1 is still being displayed, same goes for the 3,4,5.... values being sent.
Debugging the code shows i send the correct values each time to the engine, and the engine replies with a 200 status code response for each event being sent.

My OLED works on all other apps and displays GIFS correctly.

Any help?

**Comment by JHunz** [comment]
Since you're not sending a value with your event, only a data frame, you should make sure to specify the value_optional property when binding the event to prevent caching behavior interfering like this.

**Comment by EranVazana** [comment]
> 
> 
> Since you're not sending a value with your event, only a data frame, you should make sure to specify the value_optional property when binding the event to prevent caching behavior interfering like this.

Thanks! this seems to do the trick :)
