### ISSUE TITLE
Color zones on the Msi Mpg341cqr

### ISSUE THREAD

**Issue by BestBoyBerlin** [SteelSeries/gamesense-sdk#91]
In the documentation, many color zones are listed. Also some for Msi monitors. My monitor is not listed and i have no clue how to access the different zones. Is there an update planned to support my monitor or am I just not finding the right setting?

**Comment by JHunz** [comment]
Does the monitor show up in the devices listed in the Gear tab of SteelSeries Engine?  We were asked to support the MPG341CQ, but I don't believe they requested the MPG341CQR.  Unless they share a product ID and the device shows up in Engine, I won't be able to help you.

**Comment by BestBoyBerlin** [comment]
The Monitor is listed as the Mpg341cq in the gear tab and I am able to use apps like the audio visualuzer. So it is definetely supported. I just don't know how to access the zones.

**Comment by JHunz** [comment]
It should respond to "rgb-52-zone" but it looks like there's a minor bug preventing it from doing so at the moment.  I'll file that internally to get fixed.

In the meantime, you can use the device type "msi-mpg341cq" to address it specifically.  Or you can use the "rgb-zoned-device" shortcut type if you're developing an app for multiple devices.  The zones are numbered "one" to "fifty-two".

**Comment by BestBoyBerlin** [comment]
Ok thanks. Then either my code is not working because I did something wrong or it is because the bug. Either way, can you tell me when it is fixed and should work with rgb-52-zone?

**Comment by JHunz** [comment]
It should respond to both of the specifiers above as of engine version 3.18.4 yesterday
