### ISSUE TITLE
Context Color doesn't work

### ISSUE THREAD

**Issue by BestBoyBerlin** [SteelSeries/gamesense-sdk#92]
Is there a way of sending color instead of only sending an int value to the game_event endpoint? And if there is a way, is it required to configure the bind_game_event in a specific way?

**Comment by JHunz** [comment]
The "context-color" lighting mode allows you to always pull the color from the additional context data sent with the event.  It's documented here: https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/json-handlers-color.md#dynamic-color-via-context-data

**Comment by BestBoyBerlin** [comment]
[ContextColor.txt](https://github.com/SteelSeries/gamesense-sdk/files/5086435/ContextColor.txt)

I tried the  "context-color" lighting, but it isn't working for me. The light just turns off, even when i was sending rgb color that should display just blue for example or even complete white.

**Comment by BestBoyBerlin** [comment]
Latest version fixed the bug and it works now
