### ISSUE TITLE
Is it possible to display a text line with inverse video attribute on the OLED screen of a SteelSeries keyboard ?

### ISSUE THREAD

**Issue by Morbius01** [SteelSeries/gamesense-sdk#98]
The Text Formatting Options section on the https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/json-handlers-screen.md#text-formatting-options page explains how to display text on the OLED screen of a SteelSeries device with the 'bold' attribute.

I was wondering if it is possible to display text in inverse video (foreground : black; background : white) to the OLED screen of my SteelSeries Apex 5 keyboard.

Can anybody help ?

**Comment by JHunz** [comment]
We don't currently have an option or flag for reversing the text and foreground colors.  As a workaround, however, your app could pre-render the text that way into an image and use image handlers instead.
